/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Coffee } from "./Coffee";
export * as factories from "./factories";
export { Coffee__factory } from "./factories/Coffee__factory";
